// Australian visa subclasses and states data

export interface VisaSubclass {
   code: string;
   name: string;
   label: string; // Combined format: "189 - Skilled Independent"
}

export interface AustralianState {
   code: string;
   name: string;
}

// Australian Visa Subclasses
export const AUSTRALIAN_VISA_SUBCLASSES: VisaSubclass[] = [
   {
      code: "189",
      name: "Skilled Independent",
      label: "189 - Skilled Independent",
   },
   { code: "190", name: "Skilled Nominated", label: "190 - Skilled Nominated" },
   {
      code: "491",
      name: "Skilled Work Regional (Provisional)",
      label: "491 - Skilled Work Regional (Provisional)",
   },
   {
      code: "482",
      name: "Temporary Skill Shortage",
      label: "482 - Temporary Skill Shortage",
   },
   {
      code: "186",
      name: "Employer Nomination Scheme",
      label: "186 - Employer Nomination Scheme",
   },
   {
      code: "494",
      name: "Skilled Employer Sponsored Regional (Provisional)",
      label: "494 - Skilled Employer Sponsored Regional (Provisional)",
   },
   {
      code: "191",
      name: "Permanent Residence (Skilled Regional)",
      label: "191 - Permanent Residence (Skilled Regional)",
   },
   {
      code: "485",
      name: "Temporary Graduate",
      label: "485 - Temporary Graduate",
   },
   { code: "407", name: "Training", label: "407 - Training" },
   {
      code: "400",
      name: "Temporary Work (Short Stay Specialist)",
      label: "400 - Temporary Work (Short Stay Specialist)",
   },
   {
      code: "188",
      name: "Business Innovation and Investment (Provisional)",
      label: "188 - Business Innovation and Investment (Provisional)",
   },
   {
      code: "888",
      name: "Business Innovation and Investment (Permanent)",
      label: "888 - Business Innovation and Investment (Permanent)",
   },
   {
      code: "132",
      name: "Business Talent (Permanent)",
      label: "132 - Business Talent (Permanent)",
   },
   { code: "500", name: "Student", label: "500 - Student" },
   { code: "600", name: "Visitor", label: "600 - Visitor" },
   {
      code: "820",
      name: "Partner (Temporary)",
      label: "820 - Partner (Temporary)",
   },
   { code: "801", name: "Partner (Migrant)", label: "801 - Partner (Migrant)" },
   {
      code: "309",
      name: "Partner (Provisional)",
      label: "309 - Partner (Provisional)",
   },
   {
      code: "100",
      name: "Partner (Residence)",
      label: "100 - Partner (Residence)",
   },
   {
      code: "143",
      name: "Contributory Parent",
      label: "143 - Contributory Parent",
   },
   {
      code: "173",
      name: "Contributory Parent (Temporary)",
      label: "173 - Contributory Parent (Temporary)",
   },
   { code: "103", name: "Parent", label: "103 - Parent" },
   { code: "804", name: "Aged Parent", label: "804 - Aged Parent" },
   {
      code: "884",
      name: "Contributory Aged Parent (Temporary)",
      label: "884 - Contributory Aged Parent (Temporary)",
   },
   {
      code: "864",
      name: "Contributory Aged Parent",
      label: "864 - Contributory Aged Parent",
   },
];

// Australian States and Territories
export const AUSTRALIAN_STATES: AustralianState[] = [
   { code: "NSW", name: "New South Wales" },
   { code: "VIC", name: "Victoria" },
   { code: "QLD", name: "Queensland" },
   { code: "SA", name: "South Australia" },
   { code: "WA", name: "Western Australia" },
   { code: "TAS", name: "Tasmania" },
   { code: "NT", name: "Northern Territory" },
   { code: "ACT", name: "Australian Capital Territory" },
];

// Helper functions for searching and filtering

export function searchVisaSubclasses(query: string): VisaSubclass[] {
   if (!query) return AUSTRALIAN_VISA_SUBCLASSES;

   const lowerQuery = query.toLowerCase();
   return AUSTRALIAN_VISA_SUBCLASSES.filter(
      (subclass) =>
         subclass.code.toLowerCase().includes(lowerQuery) ||
         subclass.name.toLowerCase().includes(lowerQuery) ||
         subclass.label.toLowerCase().includes(lowerQuery)
   );
}

export function searchStates(query: string): AustralianState[] {
   if (!query) return AUSTRALIAN_STATES;

   const lowerQuery = query.toLowerCase();
   return AUSTRALIAN_STATES.filter(
      (state) =>
         state.code.toLowerCase().includes(lowerQuery) ||
         state.name.toLowerCase().includes(lowerQuery)
   );
}

export function getVisaSubclassByCode(code: string): VisaSubclass | undefined {
   return AUSTRALIAN_VISA_SUBCLASSES.find((s) => s.code === code);
}

export function getStateByCode(code: string): AustralianState | undefined {
   return AUSTRALIAN_STATES.find((s) => s.code === code);
}

// ANZSCO Codes with Assessing Authorities
export interface AnzscoCode {
   anzsco_code: string;
   name: string;
   assessing_authority: string;
}

export const ANZSCO_CODES: AnzscoCode[] = [
   { anzsco_code: "121111", name: "Aquaculture Farmer", assessing_authority: "VETASSESS" },
   { anzsco_code: "121211", name: "Cotton Grower", assessing_authority: "VETASSESS" },
   { anzsco_code: "121212", name: "Flower Grower", assessing_authority: "VETASSESS" },
   { anzsco_code: "121213", name: "Fruit or Nut Grower", assessing_authority: "VETASSESS" },
   { anzsco_code: "121214", name: "Grain, Oilseed or Pasture Grower", assessing_authority: "VETASSESS" },
   { anzsco_code: "121215", name: "Grape Grower", assessing_authority: "VETASSESS" },
   { anzsco_code: "121216", name: "Mixed Crop Farmer", assessing_authority: "VETASSESS" },
   { anzsco_code: "121217", name: "Sugar Cane Grower", assessing_authority: "VETASSESS" },
   { anzsco_code: "121221", name: "Vegetable Grower", assessing_authority: "VETASSESS" },
   { anzsco_code: "121299", name: "Crop Farmers nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "133111", name: "Construction Project Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "133112", name: "Project Builder", assessing_authority: "VETASSESS" },
   { anzsco_code: "133211", name: "Engineering Manager", assessing_authority: "Engineers Australia" },
   { anzsco_code: "133411", name: "Manufacturing Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "133511", name: "Production Manager (Forestry)", assessing_authority: "VETASSESS" },
   { anzsco_code: "133512", name: "Production Manager (Manufacturing)", assessing_authority: "VETASSESS" },
   { anzsco_code: "133513", name: "Production Manager (Mining)", assessing_authority: "VETASSESS" },
   { anzsco_code: "134111", name: "Child Care Centre Manager", assessing_authority: "ACECQA" },
   { anzsco_code: "134211", name: "Medical Administrator", assessing_authority: "VETASSESS" },
   { anzsco_code: "134212", name: "Nursing Clinical Director", assessing_authority: "ANMAC" },
   { anzsco_code: "134213", name: "Primary Health Organisation Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "134214", name: "Welfare Centre Manager", assessing_authority: "ACWA" },
   { anzsco_code: "135111", name: "Chief Information Officer", assessing_authority: "ACS" },
   { anzsco_code: "135112", name: "ICT Project Manager", assessing_authority: "ACS" },
   { anzsco_code: "135199", name: "ICT Managers nec", assessing_authority: "ACS" },
   { anzsco_code: "139911", name: "Arts Administrator or Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "139912", name: "Environmental Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "139913", name: "Laboratory Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "139914", name: "Quality Assurance Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "139999", name: "Specialist Managers nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "141111", name: "Cafe or Restaurant Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "141211", name: "Hotel or Motel Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "141311", name: "Licensed Club Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "141411", name: "Retail Manager (General)", assessing_authority: "VETASSESS" },
   { anzsco_code: "149111", name: "Amusement Centre Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "149112", name: "Fitness Centre Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "149113", name: "Sports Centre Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "149211", name: "Call or Contact Centre Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "149212", name: "Customer Service Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "149311", name: "Conference and Event Organiser", assessing_authority: "VETASSESS" },
   { anzsco_code: "149411", name: "Fleet Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "149412", name: "Railway Station Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "149413", name: "Transport Company Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "149911", name: "Facilities Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "149912", name: "Financial Institution Branch Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "149913", name: "Post Office Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "149999", name: "Miscellaneous Hospitality, Retail and Service Managers nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "211111", name: "Actuary", assessing_authority: "VETASSESS" },
   { anzsco_code: "211211", name: "Chemist", assessing_authority: "VETASSESS" },
   { anzsco_code: "211212", name: "Food Technologist", assessing_authority: "VETASSESS" },
   { anzsco_code: "211213", name: "Wine Maker", assessing_authority: "VETASSESS" },
   { anzsco_code: "211299", name: "Life Scientists nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "211311", name: "Forester", assessing_authority: "VETASSESS" },
   { anzsco_code: "211399", name: "Agricultural, Forestry and Horticultural Plant Scientists nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "211411", name: "Conservation Officer", assessing_authority: "VETASSESS" },
   { anzsco_code: "211412", name: "Environmental Consultant", assessing_authority: "VETASSESS" },
   { anzsco_code: "211413", name: "Environmental Research Scientist", assessing_authority: "VETASSESS" },
   { anzsco_code: "211499", name: "Environmental Scientists nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "212111", name: "Commodities Trader", assessing_authority: "VETASSESS" },
   { anzsco_code: "212112", name: "Financial Investment Adviser", assessing_authority: "VETASSESS" },
   { anzsco_code: "212113", name: "Financial Investment Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "212211", name: "Corporate Treasurer", assessing_authority: "VETASSESS" },
   { anzsco_code: "212212", name: "Finance Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "212311", name: "Human Resource Adviser", assessing_authority: "VETASSESS" },
   { anzsco_code: "212312", name: "Recruitment Consultant", assessing_authority: "VETASSESS" },
   { anzsco_code: "212313", name: "Workplace Relations Adviser", assessing_authority: "VETASSESS" },
   { anzsco_code: "212314", name: "Human Resource Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "212315", name: "Training and Development Professional", assessing_authority: "VETASSESS" },
   { anzsco_code: "212316", name: "Organisation and Methods Analyst", assessing_authority: "VETASSESS" },
   { anzsco_code: "212317", name: "Information and Organisation Professionals nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "212411", name: "Policy Analyst", assessing_authority: "VETASSESS" },
   { anzsco_code: "212412", name: "Liaison Officer", assessing_authority: "VETASSESS" },
   { anzsco_code: "212413", name: "Migration Agent", assessing_authority: "MARA" },
   { anzsco_code: "212414", name: "Patents Examiner", assessing_authority: "VETASSESS" },
   { anzsco_code: "212415", name: "Compliance Officer", assessing_authority: "VETASSESS" },
   { anzsco_code: "212416", name: "Court Bailiff or Sheriff", assessing_authority: "VETASSESS" },
   { anzsco_code: "212417", name: "Insurance Loss Adjuster", assessing_authority: "VETASSESS" },
   { anzsco_code: "212418", name: "Insurance Risk Surveyor", assessing_authority: "VETASSESS" },
   { anzsco_code: "212499", name: "Business and Systems Analysts, and Programmers nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "221111", name: "Accountant (General)", assessing_authority: "CPAA / CAANZ / IPA" },
   { anzsco_code: "221112", name: "Management Accountant", assessing_authority: "CPAA / CAANZ / IPA" },
   { anzsco_code: "221113", name: "Taxation Accountant", assessing_authority: "CPAA / CAANZ / IPA" },
   { anzsco_code: "221211", name: "Company Secretary", assessing_authority: "VETASSESS" },
   { anzsco_code: "221212", name: "Corporate Treasurer", assessing_authority: "VETASSESS" },
   { anzsco_code: "222111", name: "Commodities Trader", assessing_authority: "VETASSESS" },
   { anzsco_code: "222112", name: "Finance Broker", assessing_authority: "VETASSESS" },
   { anzsco_code: "222113", name: "Insurance Broker", assessing_authority: "VETASSESS" },
   { anzsco_code: "222199", name: "Financial Brokers nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "222211", name: "Financial Market Dealer", assessing_authority: "VETASSESS" },
   { anzsco_code: "222212", name: "Futures Trader", assessing_authority: "VETASSESS" },
   { anzsco_code: "222213", name: "Stockbroker", assessing_authority: "VETASSESS" },
   { anzsco_code: "222299", name: "Financial Dealers nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "222311", name: "Financial Investment Adviser", assessing_authority: "VETASSESS" },
   { anzsco_code: "222312", name: "Financial Investment Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "223111", name: "Human Resource Adviser", assessing_authority: "VETASSESS" },
   { anzsco_code: "223112", name: "Recruitment Consultant", assessing_authority: "VETASSESS" },
   { anzsco_code: "223113", name: "Workplace Relations Adviser", assessing_authority: "VETASSESS" },
   { anzsco_code: "224111", name: "Actuary", assessing_authority: "VETASSESS" },
   { anzsco_code: "224112", name: "Mathematician", assessing_authority: "VETASSESS" },
   { anzsco_code: "224113", name: "Statistician", assessing_authority: "VETASSESS" },
   { anzsco_code: "224211", name: "Archivist", assessing_authority: "VETASSESS" },
   { anzsco_code: "224212", name: "Gallery or Museum Curator", assessing_authority: "VETASSESS" },
   { anzsco_code: "224213", name: "Health Information Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "224214", name: "Records Manager", assessing_authority: "VETASSESS" },
   { anzsco_code: "224311", name: "Economist", assessing_authority: "VETASSESS" },
   { anzsco_code: "224312", name: "Policy Analyst", assessing_authority: "VETASSESS" },
   { anzsco_code: "224411", name: "Intelligence Officer", assessing_authority: "VETASSESS" },
   { anzsco_code: "224412", name: "Interpreter", assessing_authority: "NAATI" },
   { anzsco_code: "224413", name: "Translator", assessing_authority: "NAATI" },
   { anzsco_code: "224511", name: "Land Economist", assessing_authority: "VETASSESS" },
   { anzsco_code: "224512", name: "Valuer", assessing_authority: "VETASSESS" },
   { anzsco_code: "224611", name: "Librarian", assessing_authority: "VETASSESS" },
   { anzsco_code: "224711", name: "Management Consultant", assessing_authority: "VETASSESS" },
   { anzsco_code: "224712", name: "Organisation and Methods Analyst", assessing_authority: "VETASSESS" },
   { anzsco_code: "224911", name: "Electorate Officer", assessing_authority: "VETASSESS" },
   { anzsco_code: "224912", name: "Liaison Officer", assessing_authority: "VETASSESS" },
   { anzsco_code: "224913", name: "Migration Agent", assessing_authority: "MARA" },
   { anzsco_code: "224914", name: "Patents Examiner", assessing_authority: "VETASSESS" },
   { anzsco_code: "224999", name: "Information and Organisation Professionals nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "231111", name: "Aeroplane Pilot", assessing_authority: "CASA" },
   { anzsco_code: "231112", name: "Air Traffic Controller", assessing_authority: "CASA" },
   { anzsco_code: "231113", name: "Flying Instructor", assessing_authority: "CASA" },
   { anzsco_code: "231114", name: "Helicopter Pilot", assessing_authority: "CASA" },
   { anzsco_code: "231199", name: "Air Transport Professionals nec", assessing_authority: "CASA" },
   { anzsco_code: "232111", name: "Architect", assessing_authority: "AACA" },
   { anzsco_code: "232112", name: "Landscape Architect", assessing_authority: "VETASSESS" },
   { anzsco_code: "232211", name: "Cartographer", assessing_authority: "VETASSESS" },
   { anzsco_code: "232212", name: "Other Spatial Scientist", assessing_authority: "VETASSESS" },
   { anzsco_code: "232311", name: "Fashion Designer", assessing_authority: "VETASSESS" },
   { anzsco_code: "232312", name: "Industrial Designer", assessing_authority: "VETASSESS" },
   { anzsco_code: "232313", name: "Jewellery Designer", assessing_authority: "VETASSESS" },
   { anzsco_code: "232411", name: "Graphic Designer", assessing_authority: "VETASSESS" },
   { anzsco_code: "232412", name: "Illustrator", assessing_authority: "VETASSESS" },
   { anzsco_code: "232413", name: "Multimedia Designer", assessing_authority: "VETASSESS" },
   { anzsco_code: "232414", name: "Web Designer", assessing_authority: "VETASSESS" },
   { anzsco_code: "232511", name: "Interior Designer", assessing_authority: "VETASSESS" },
   { anzsco_code: "233111", name: "Chemical Engineer", assessing_authority: "Engineers Australia" },
   { anzsco_code: "233112", name: "Materials Engineer", assessing_authority: "Engineers Australia" },
   { anzsco_code: "233211", name: "Civil Engineer", assessing_authority: "Engineers Australia" },
   { anzsco_code: "233212", name: "Geotechnical Engineer", assessing_authority: "Engineers Australia" },
   { anzsco_code: "233213", name: "Quantity Surveyor", assessing_authority: "AIQS" },
   { anzsco_code: "233214", name: "Structural Engineer", assessing_authority: "Engineers Australia" },
   { anzsco_code: "233215", name: "Transport Engineer", assessing_authority: "Engineers Australia" },
   { anzsco_code: "233311", name: "Electrical Engineer", assessing_authority: "Engineers Australia" },
   { anzsco_code: "233411", name: "Electronics Engineer", assessing_authority: "Engineers Australia" },
   { anzsco_code: "233511", name: "Industrial Engineer", assessing_authority: "Engineers Australia" },
   { anzsco_code: "233512", name: "Mechanical Engineer", assessing_authority: "Engineers Australia" },
   { anzsco_code: "233611", name: "Mining Engineer (excluding Petroleum)", assessing_authority: "Engineers Australia" },
   { anzsco_code: "233612", name: "Petroleum Engineer", assessing_authority: "Engineers Australia" },
   { anzsco_code: "233911", name: "Aeronautical Engineer", assessing_authority: "Engineers Australia" },
   { anzsco_code: "233912", name: "Agricultural Engineer", assessing_authority: "Engineers Australia" },
   { anzsco_code: "233913", name: "Biomedical Engineer", assessing_authority: "Engineers Australia" },
   { anzsco_code: "233914", name: "Engineering Technologist", assessing_authority: "Engineers Australia" },
   { anzsco_code: "233915", name: "Environmental Engineer", assessing_authority: "Engineers Australia" },
   { anzsco_code: "233916", name: "Naval Architect", assessing_authority: "Engineers Australia" },
   { anzsco_code: "233999", name: "Engineering Professionals nec", assessing_authority: "Engineers Australia" },
   { anzsco_code: "234111", name: "Agricultural Consultant", assessing_authority: "VETASSESS" },
   { anzsco_code: "234112", name: "Agricultural Scientist", assessing_authority: "VETASSESS" },
   { anzsco_code: "234113", name: "Forester", assessing_authority: "VETASSESS" },
   { anzsco_code: "234211", name: "Chemist", assessing_authority: "VETASSESS" },
   { anzsco_code: "234212", name: "Food Technologist", assessing_authority: "VETASSESS" },
   { anzsco_code: "234311", name: "Conservation Officer", assessing_authority: "VETASSESS" },
   { anzsco_code: "234312", name: "Environmental Consultant", assessing_authority: "VETASSESS" },
   { anzsco_code: "234313", name: "Environmental Research Scientist", assessing_authority: "VETASSESS" },
   { anzsco_code: "234399", name: "Environmental Scientists nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "234411", name: "Geologist", assessing_authority: "VETASSESS" },
   { anzsco_code: "234412", name: "Geophysicist", assessing_authority: "VETASSESS" },
   { anzsco_code: "234413", name: "Hydrogeologist", assessing_authority: "VETASSESS" },
   { anzsco_code: "234511", name: "Life Scientist (General)", assessing_authority: "VETASSESS" },
   { anzsco_code: "234512", name: "Biochemist", assessing_authority: "VETASSESS" },
   { anzsco_code: "234513", name: "Biotechnologist", assessing_authority: "VETASSESS" },
   { anzsco_code: "234514", name: "Botanist", assessing_authority: "VETASSESS" },
   { anzsco_code: "234515", name: "Marine Biologist", assessing_authority: "VETASSESS" },
   { anzsco_code: "234516", name: "Microbiologist", assessing_authority: "VETASSESS" },
   { anzsco_code: "234517", name: "Zoologist", assessing_authority: "VETASSESS" },
   { anzsco_code: "234518", name: "Life Scientists nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "234611", name: "Medical Laboratory Scientist", assessing_authority: "AIMS" },
   { anzsco_code: "234711", name: "Veterinarian", assessing_authority: "AVBC" },
   { anzsco_code: "234911", name: "Conservation Officer", assessing_authority: "VETASSESS" },
   { anzsco_code: "234912", name: "Metallurgist", assessing_authority: "VETASSESS" },
   { anzsco_code: "234913", name: "Meteorologist", assessing_authority: "VETASSESS" },
   { anzsco_code: "234914", name: "Physicist", assessing_authority: "VETASSESS" },
   { anzsco_code: "234999", name: "Natural and Physical Science Professionals nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "241111", name: "Early Childhood (Pre-primary School) Teacher", assessing_authority: "AITSL" },
   { anzsco_code: "241211", name: "Primary School Teacher", assessing_authority: "AITSL" },
   { anzsco_code: "241311", name: "Middle School Teacher", assessing_authority: "AITSL" },
   { anzsco_code: "241411", name: "Secondary School Teacher", assessing_authority: "AITSL" },
   { anzsco_code: "241511", name: "Special Needs Teacher", assessing_authority: "AITSL" },
   { anzsco_code: "241512", name: "Teacher of the Hearing Impaired", assessing_authority: "AITSL" },
   { anzsco_code: "241513", name: "Teacher of the Sight Impaired", assessing_authority: "AITSL" },
   { anzsco_code: "241599", name: "Special Education Teachers nec", assessing_authority: "AITSL" },
   { anzsco_code: "242111", name: "University Lecturer", assessing_authority: "VETASSESS" },
   { anzsco_code: "251111", name: "Dietitian", assessing_authority: "DAA" },
   { anzsco_code: "251211", name: "Medical Diagnostic Radiographer", assessing_authority: "ASMIRT" },
   { anzsco_code: "251212", name: "Medical Radiation Therapist", assessing_authority: "ASMIRT" },
   { anzsco_code: "251213", name: "Nuclear Medicine Technologist", assessing_authority: "ANZSNM" },
   { anzsco_code: "251214", name: "Sonographer", assessing_authority: "ASMIRT" },
   { anzsco_code: "251311", name: "Environmental Health Officer", assessing_authority: "VETASSESS" },
   { anzsco_code: "251312", name: "Occupational Health and Safety Adviser", assessing_authority: "VETASSESS" },
   { anzsco_code: "251411", name: "Optometrist", assessing_authority: "OCANZ" },
   { anzsco_code: "251412", name: "Orthoptist", assessing_authority: "VETASSESS" },
   { anzsco_code: "251511", name: "Hospital Pharmacist", assessing_authority: "APC" },
   { anzsco_code: "251512", name: "Industrial Pharmacist", assessing_authority: "APC" },
   { anzsco_code: "251513", name: "Retail Pharmacist", assessing_authority: "APC" },
   { anzsco_code: "251911", name: "Health Promotion Officer", assessing_authority: "VETASSESS" },
   { anzsco_code: "251912", name: "Orthotist or Prosthetist", assessing_authority: "VETASSESS" },
   { anzsco_code: "251999", name: "Health Diagnostic and Promotion Professionals nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "252111", name: "Chiropractor", assessing_authority: "CCEA" },
   { anzsco_code: "252112", name: "Osteopath", assessing_authority: "OCANZ" },
   { anzsco_code: "252211", name: "Acupuncturist", assessing_authority: "Chinese Medicine Board of Australia" },
   { anzsco_code: "252212", name: "Homoeopath", assessing_authority: "VETASSESS" },
   { anzsco_code: "252213", name: "Naturopath", assessing_authority: "VETASSESS" },
   { anzsco_code: "252214", name: "Traditional Chinese Medicine Practitioner", assessing_authority: "Chinese Medicine Board of Australia" },
   { anzsco_code: "252299", name: "Complementary Health Therapists nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "252311", name: "Dental Specialist", assessing_authority: "ADC" },
   { anzsco_code: "252312", name: "Dentist", assessing_authority: "ADC" },
   { anzsco_code: "252411", name: "Occupational Therapist", assessing_authority: "OTASA" },
   { anzsco_code: "252412", name: "Physiotherapist", assessing_authority: "APC-PT" },
   { anzsco_code: "252511", name: "Physiotherapist", assessing_authority: "APC-PT" },
   { anzsco_code: "252611", name: "Podiatrist", assessing_authority: "ANZPAC" },
   { anzsco_code: "252711", name: "Audiologist", assessing_authority: "VETASSESS" },
   { anzsco_code: "252712", name: "Speech Pathologist", assessing_authority: "SPA" },
   { anzsco_code: "253111", name: "General Practitioner", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253112", name: "Resident Medical Officer", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253211", name: "Anaesthetist", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253311", name: "Specialist Physician (General Medicine)", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253312", name: "Cardiologist", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253313", name: "Clinical Haematologist", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253314", name: "Medical Oncologist", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253315", name: "Endocrinologist", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253316", name: "Gastroenterologist", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253317", name: "Intensive Care Specialist", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253318", name: "Neurologist", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253321", name: "Paediatrician", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253322", name: "Renal Medicine Specialist", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253323", name: "Rheumatologist", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253324", name: "Thoracic Medicine Specialist", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253399", name: "Specialist Physicians nec", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253411", name: "Psychiatrist", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253511", name: "Surgeon (General)", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253512", name: "Cardiothoracic Surgeon", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253513", name: "Neurosurgeon", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253514", name: "Orthopaedic Surgeon", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253515", name: "Otorhinolaryngologist", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253516", name: "Paediatric Surgeon", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253517", name: "Plastic and Reconstructive Surgeon", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253518", name: "Urologist", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253521", name: "Vascular Surgeon", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253911", name: "Dermatologist", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253912", name: "Emergency Medicine Specialist", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253913", name: "Obstetrician and Gynaecologist", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253914", name: "Ophthalmologist", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253915", name: "Pathologist", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253916", name: "Diagnostic and Interventional Radiologist", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253917", name: "Radiation Oncologist", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "253999", name: "Medical Practitioners nec", assessing_authority: "Medical Board of Australia" },
   { anzsco_code: "254111", name: "Midwife", assessing_authority: "ANMAC" },
   { anzsco_code: "254211", name: "Nurse Educator", assessing_authority: "ANMAC" },
   { anzsco_code: "254311", name: "Nurse Manager", assessing_authority: "ANMAC" },
   { anzsco_code: "254411", name: "Nurse Practitioner", assessing_authority: "ANMAC" },
   { anzsco_code: "254412", name: "Registered Nurse (Aged Care)", assessing_authority: "ANMAC" },
   { anzsco_code: "254413", name: "Registered Nurse (Child and Family Health)", assessing_authority: "ANMAC" },
   { anzsco_code: "254414", name: "Registered Nurse (Community Health)", assessing_authority: "ANMAC" },
   { anzsco_code: "254415", name: "Registered Nurse (Critical Care and Emergency)", assessing_authority: "ANMAC" },
   { anzsco_code: "254416", name: "Registered Nurse (Developmental Disability)", assessing_authority: "ANMAC" },
   { anzsco_code: "254417", name: "Registered Nurse (Disability and Rehabilitation)", assessing_authority: "ANMAC" },
   { anzsco_code: "254418", name: "Registered Nurse (Medical)", assessing_authority: "ANMAC" },
   { anzsco_code: "254421", name: "Registered Nurse (Medical Practice)", assessing_authority: "ANMAC" },
   { anzsco_code: "254422", name: "Registered Nurse (Mental Health)", assessing_authority: "ANMAC" },
   { anzsco_code: "254423", name: "Registered Nurse (Perioperative)", assessing_authority: "ANMAC" },
   { anzsco_code: "254424", name: "Registered Nurse (Surgical)", assessing_authority: "ANMAC" },
   { anzsco_code: "254425", name: "Registered Nurse (Paediatric)", assessing_authority: "ANMAC" },
   { anzsco_code: "254499", name: "Registered Nurses nec", assessing_authority: "ANMAC" },
   { anzsco_code: "261111", name: "ICT Business Analyst", assessing_authority: "ACS" },
   { anzsco_code: "261112", name: "Systems Analyst", assessing_authority: "ACS" },
   { anzsco_code: "261211", name: "Multimedia Specialist", assessing_authority: "ACS" },
   { anzsco_code: "261212", name: "Web Developer", assessing_authority: "ACS" },
   { anzsco_code: "261311", name: "Analyst Programmer", assessing_authority: "ACS" },
   { anzsco_code: "261312", name: "Developer Programmer", assessing_authority: "ACS" },
   { anzsco_code: "261313", name: "Software Engineer", assessing_authority: "ACS" },
   { anzsco_code: "261314", name: "Software Tester", assessing_authority: "ACS" },
   { anzsco_code: "261399", name: "Software and Applications Programmers nec", assessing_authority: "ACS" },
   { anzsco_code: "262111", name: "Database Administrator", assessing_authority: "ACS" },
   { anzsco_code: "262112", name: "ICT Security Specialist", assessing_authority: "ACS" },
   { anzsco_code: "262113", name: "Systems Administrator", assessing_authority: "ACS" },
   { anzsco_code: "263111", name: "Computer Network and Systems Engineer", assessing_authority: "ACS" },
   { anzsco_code: "263112", name: "Network Administrator", assessing_authority: "ACS" },
   { anzsco_code: "263113", name: "Network Analyst", assessing_authority: "ACS" },
   { anzsco_code: "263211", name: "ICT Quality Assurance Engineer", assessing_authority: "ACS" },
   { anzsco_code: "263212", name: "ICT Support Engineer", assessing_authority: "ACS" },
   { anzsco_code: "263213", name: "ICT Systems Test Engineer", assessing_authority: "ACS" },
   { anzsco_code: "263299", name: "ICT Support and Test Engineers nec", assessing_authority: "ACS" },
   { anzsco_code: "263311", name: "Telecommunications Engineer", assessing_authority: "Engineers Australia" },
   { anzsco_code: "263312", name: "Telecommunications Network Engineer", assessing_authority: "Engineers Australia" },
   { anzsco_code: "271111", name: "Barrister", assessing_authority: "SLAA" },
   { anzsco_code: "271211", name: "Judge", assessing_authority: "SLAA" },
   { anzsco_code: "271299", name: "Judicial and Other Legal Professionals nec", assessing_authority: "SLAA" },
   { anzsco_code: "271311", name: "Solicitor", assessing_authority: "SLAA" },
   { anzsco_code: "272111", name: "Career Counsellor", assessing_authority: "VETASSESS" },
   { anzsco_code: "272112", name: "Drug and Alcohol Counsellor", assessing_authority: "VETASSESS" },
   { anzsco_code: "272113", name: "Family and Marriage Counsellor", assessing_authority: "VETASSESS" },
   { anzsco_code: "272114", name: "Rehabilitation Counsellor", assessing_authority: "VETASSESS" },
   { anzsco_code: "272115", name: "Student Counsellor", assessing_authority: "VETASSESS" },
   { anzsco_code: "272199", name: "Counsellors nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "272211", name: "Minister of Religion", assessing_authority: "VETASSESS" },
   { anzsco_code: "272299", name: "Religious Professionals nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "272311", name: "Clinical Psychologist", assessing_authority: "APS" },
   { anzsco_code: "272312", name: "Educational Psychologist", assessing_authority: "APS" },
   { anzsco_code: "272313", name: "Organisational Psychologist", assessing_authority: "APS" },
   { anzsco_code: "272314", name: "Psychotherapist", assessing_authority: "VETASSESS" },
   { anzsco_code: "272399", name: "Psychologists nec", assessing_authority: "APS" },
   { anzsco_code: "272411", name: "Historian", assessing_authority: "VETASSESS" },
   { anzsco_code: "272412", name: "Translator", assessing_authority: "NAATI" },
   { anzsco_code: "272413", name: "Interpreter", assessing_authority: "NAATI" },
   { anzsco_code: "272499", name: "Social Professionals nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "272511", name: "Social Worker", assessing_authority: "AASW" },
   { anzsco_code: "272612", name: "Recreation Officer", assessing_authority: "VETASSESS" },
   { anzsco_code: "272613", name: "Welfare Worker", assessing_authority: "ACWA" },
   { anzsco_code: "311111", name: "Agricultural Technician", assessing_authority: "VETASSESS" },
   { anzsco_code: "311211", name: "Chemical Technician", assessing_authority: "VETASSESS" },
   { anzsco_code: "311212", name: "Earth Science Technician", assessing_authority: "VETASSESS" },
   { anzsco_code: "311213", name: "Life Science Technician", assessing_authority: "VETASSESS" },
   { anzsco_code: "311214", name: "School Laboratory Technician", assessing_authority: "VETASSESS" },
   { anzsco_code: "311299", name: "Science Technicians nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "311311", name: "Agricultural Engineer", assessing_authority: "Engineers Australia" },
   { anzsco_code: "311312", name: "Biomedical Engineer", assessing_authority: "Engineers Australia" },
   { anzsco_code: "311411", name: "Chemistry Laboratory Technician", assessing_authority: "VETASSESS" },
   { anzsco_code: "311412", name: "Earth Science Technician", assessing_authority: "VETASSESS" },
   { anzsco_code: "311413", name: "Life Science Technician", assessing_authority: "VETASSESS" },
   { anzsco_code: "311499", name: "Science Technicians nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "312111", name: "Architectural Draftsperson", assessing_authority: "VETASSESS" },
   { anzsco_code: "312112", name: "Building Associate", assessing_authority: "VETASSESS" },
   { anzsco_code: "312113", name: "Building Inspector", assessing_authority: "VETASSESS" },
   { anzsco_code: "312114", name: "Construction Estimator", assessing_authority: "VETASSESS" },
   { anzsco_code: "312115", name: "Plumbing Inspector", assessing_authority: "VETASSESS" },
   { anzsco_code: "312116", name: "Surveying or Spatial Science Technician", assessing_authority: "VETASSESS" },
   { anzsco_code: "312199", name: "Architectural, Building and Surveying Technicians nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "312211", name: "Civil Engineering Draftsperson", assessing_authority: "Engineers Australia" },
   { anzsco_code: "312212", name: "Civil Engineering Technician", assessing_authority: "Engineers Australia" },
   { anzsco_code: "312311", name: "Electrical Engineering Draftsperson", assessing_authority: "Engineers Australia" },
   { anzsco_code: "312312", name: "Electrical Engineering Technician", assessing_authority: "Engineers Australia" },
   { anzsco_code: "312411", name: "Electronic Engineering Draftsperson", assessing_authority: "Engineers Australia" },
   { anzsco_code: "312412", name: "Electronic Engineering Technician", assessing_authority: "Engineers Australia" },
   { anzsco_code: "312511", name: "Mechanical Engineering Draftsperson", assessing_authority: "Engineers Australia" },
   { anzsco_code: "312512", name: "Mechanical Engineering Technician", assessing_authority: "Engineers Australia" },
   { anzsco_code: "312611", name: "Safety Inspector", assessing_authority: "VETASSESS" },
   { anzsco_code: "312911", name: "Maintenance Planner", assessing_authority: "VETASSESS" },
   { anzsco_code: "312912", name: "Metallurgical or Materials Technician", assessing_authority: "VETASSESS" },
   { anzsco_code: "312913", name: "Mine Deputy", assessing_authority: "VETASSESS" },
   { anzsco_code: "312999", name: "Engineering Technicians nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "313111", name: "Hardware Technician", assessing_authority: "ACS" },
   { anzsco_code: "313112", name: "ICT Customer Support Officer", assessing_authority: "ACS" },
   { anzsco_code: "313113", name: "Web Administrator", assessing_authority: "ACS" },
   { anzsco_code: "313199", name: "ICT Support Technicians nec", assessing_authority: "ACS" },
   { anzsco_code: "313211", name: "Radiocommunications Technician", assessing_authority: "VETASSESS" },
   { anzsco_code: "313212", name: "Telecommunications Field Engineer", assessing_authority: "VETASSESS" },
   { anzsco_code: "313213", name: "Telecommunications Network Planner", assessing_authority: "VETASSESS" },
   { anzsco_code: "313214", name: "Telecommunications Technical Officer or Technologist", assessing_authority: "VETASSESS" },
   { anzsco_code: "321111", name: "Automotive Electrician", assessing_authority: "TRA" },
   { anzsco_code: "321211", name: "Motor Mechanic (General)", assessing_authority: "TRA" },
   { anzsco_code: "321212", name: "Motorcycle Mechanic", assessing_authority: "TRA" },
   { anzsco_code: "321213", name: "Diesel Motor Mechanic", assessing_authority: "TRA" },
   { anzsco_code: "321214", name: "Small Engine Mechanic", assessing_authority: "TRA" },
   { anzsco_code: "322211", name: "Sheetmetal Trades Worker", assessing_authority: "TRA" },
   { anzsco_code: "322311", name: "Metal Fabricator", assessing_authority: "TRA" },
   { anzsco_code: "322312", name: "Pressure Welder", assessing_authority: "TRA" },
   { anzsco_code: "322313", name: "Welder (First Class)", assessing_authority: "TRA" },
   { anzsco_code: "323111", name: "Aircraft Maintenance Engineer (Avionics)", assessing_authority: "TRA" },
   { anzsco_code: "323112", name: "Aircraft Maintenance Engineer (Mechanical)", assessing_authority: "TRA" },
   { anzsco_code: "323113", name: "Aircraft Maintenance Engineer (Structures)", assessing_authority: "TRA" },
   { anzsco_code: "323211", name: "Fitter (General)", assessing_authority: "TRA" },
   { anzsco_code: "323212", name: "Fitter and Turner", assessing_authority: "TRA" },
   { anzsco_code: "323213", name: "Fitter-Welder", assessing_authority: "TRA" },
   { anzsco_code: "323214", name: "Metal Machinist (First Class)", assessing_authority: "TRA" },
   { anzsco_code: "323299", name: "Metal Fitters and Machinists nec", assessing_authority: "TRA" },
   { anzsco_code: "323311", name: "Engraver", assessing_authority: "TRA" },
   { anzsco_code: "323312", name: "Gunsmith", assessing_authority: "TRA" },
   { anzsco_code: "323313", name: "Locksmith", assessing_authority: "TRA" },
   { anzsco_code: "323314", name: "Precision Instrument Maker and Repairer", assessing_authority: "TRA" },
   { anzsco_code: "323315", name: "Toolmaker", assessing_authority: "TRA" },
   { anzsco_code: "324111", name: "Panelbeater", assessing_authority: "TRA" },
   { anzsco_code: "324211", name: "Vehicle Body Builder", assessing_authority: "TRA" },
   { anzsco_code: "324212", name: "Vehicle Trimmer", assessing_authority: "TRA" },
   { anzsco_code: "331111", name: "Bricklayer", assessing_authority: "TRA" },
   { anzsco_code: "331112", name: "Stonemason", assessing_authority: "TRA" },
   { anzsco_code: "331211", name: "Carpenter and Joiner", assessing_authority: "TRA" },
   { anzsco_code: "331212", name: "Carpenter", assessing_authority: "TRA" },
   { anzsco_code: "331213", name: "Joiner", assessing_authority: "TRA" },
   { anzsco_code: "332111", name: "Floor Finisher", assessing_authority: "TRA" },
   { anzsco_code: "332211", name: "Painting Trades Worker", assessing_authority: "TRA" },
   { anzsco_code: "333111", name: "Glazier", assessing_authority: "TRA" },
   { anzsco_code: "333211", name: "Fibrous Plasterer", assessing_authority: "TRA" },
   { anzsco_code: "333212", name: "Solid Plasterer", assessing_authority: "TRA" },
   { anzsco_code: "333311", name: "Roof Tiler", assessing_authority: "TRA" },
   { anzsco_code: "333411", name: "Wall and Floor Tiler", assessing_authority: "TRA" },
   { anzsco_code: "334111", name: "Plumber (General)", assessing_authority: "TRA" },
   { anzsco_code: "334112", name: "Airconditioning and Mechanical Services Plumber", assessing_authority: "TRA" },
   { anzsco_code: "334113", name: "Drainer", assessing_authority: "TRA" },
   { anzsco_code: "334114", name: "Gasfitter", assessing_authority: "TRA" },
   { anzsco_code: "334115", name: "Roof Plumber", assessing_authority: "TRA" },
   { anzsco_code: "341111", name: "Electrician (General)", assessing_authority: "TRA" },
   { anzsco_code: "341112", name: "Electrician (Special Class)", assessing_authority: "TRA" },
   { anzsco_code: "341113", name: "Lift Mechanic", assessing_authority: "TRA" },
   { anzsco_code: "342111", name: "Airconditioning and Refrigeration Mechanic", assessing_authority: "TRA" },
   { anzsco_code: "342211", name: "Electrical Linesworker", assessing_authority: "TRA" },
   { anzsco_code: "342212", name: "Technical Cable Jointer", assessing_authority: "TRA" },
   { anzsco_code: "342311", name: "Business Machine Mechanic", assessing_authority: "TRA" },
   { anzsco_code: "342312", name: "Communications Equipment Installer", assessing_authority: "TRA" },
   { anzsco_code: "342313", name: "Electronic Equipment Trades Worker", assessing_authority: "TRA" },
   { anzsco_code: "342314", name: "Electronic Instrument Trades Worker (General)", assessing_authority: "TRA" },
   { anzsco_code: "342315", name: "Electronic Instrument Trades Worker (Special Class)", assessing_authority: "TRA" },
   { anzsco_code: "351111", name: "Baker", assessing_authority: "TRA" },
   { anzsco_code: "351211", name: "Butcher or Smallgoods Maker", assessing_authority: "TRA" },
   { anzsco_code: "351311", name: "Chef", assessing_authority: "TRA" },
   { anzsco_code: "351411", name: "Cook", assessing_authority: "TRA" },
   { anzsco_code: "361111", name: "Dog Handler or Trainer", assessing_authority: "VETASSESS" },
   { anzsco_code: "361112", name: "Horse Trainer", assessing_authority: "VETASSESS" },
   { anzsco_code: "361199", name: "Animal Attendants and Trainers nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "361211", name: "Shearer", assessing_authority: "TRA" },
   { anzsco_code: "362111", name: "Florist", assessing_authority: "VETASSESS" },
   { anzsco_code: "362211", name: "Gardener (General)", assessing_authority: "VETASSESS" },
   { anzsco_code: "362212", name: "Arborist", assessing_authority: "VETASSESS" },
   { anzsco_code: "362213", name: "Landscape Gardener", assessing_authority: "VETASSESS" },
   { anzsco_code: "362311", name: "Greenkeeper", assessing_authority: "VETASSESS" },
   { anzsco_code: "362411", name: "Nurseryperson", assessing_authority: "VETASSESS" },
   { anzsco_code: "391111", name: "Hairdresser", assessing_authority: "TRA" },
   { anzsco_code: "392111", name: "Print Finisher", assessing_authority: "VETASSESS" },
   { anzsco_code: "392112", name: "Printing Machinist", assessing_authority: "VETASSESS" },
   { anzsco_code: "392113", name: "Small Offset Printer", assessing_authority: "VETASSESS" },
   { anzsco_code: "393111", name: "Canvas or Leather Goods Maker", assessing_authority: "VETASSESS" },
   { anzsco_code: "393112", name: "Clothing Patternmaker", assessing_authority: "VETASSESS" },
   { anzsco_code: "393113", name: "Dressmaker or Tailor", assessing_authority: "VETASSESS" },
   { anzsco_code: "393211", name: "Furniture Finisher", assessing_authority: "VETASSESS" },
   { anzsco_code: "393212", name: "Picture Framer", assessing_authority: "VETASSESS" },
   { anzsco_code: "393213", name: "Wood Machinist", assessing_authority: "VETASSESS" },
   { anzsco_code: "393214", name: "Wood Turner", assessing_authority: "VETASSESS" },
   { anzsco_code: "393299", name: "Wood Machinists and Other Wood Trades Workers nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "394111", name: "Cabinetmaker", assessing_authority: "TRA" },
   { anzsco_code: "394211", name: "Boat Builder and Repairer", assessing_authority: "TRA" },
   { anzsco_code: "394212", name: "Shipwright", assessing_authority: "TRA" },
   { anzsco_code: "399111", name: "Bicycle Mechanic", assessing_authority: "VETASSESS" },
   { anzsco_code: "399112", name: "Skilled Animal Attendant", assessing_authority: "VETASSESS" },
   { anzsco_code: "399113", name: "Zookeeper", assessing_authority: "VETASSESS" },
   { anzsco_code: "399211", name: "Gas or Petroleum Operator", assessing_authority: "VETASSESS" },
   { anzsco_code: "399212", name: "Power Generation Plant Operator", assessing_authority: "VETASSESS" },
   { anzsco_code: "399311", name: "Watch and Clock Maker and Repairer", assessing_authority: "VETASSESS" },
   { anzsco_code: "399312", name: "Diver", assessing_authority: "VETASSESS" },
   { anzsco_code: "399411", name: "Furniture Finisher", assessing_authority: "VETASSESS" },
   { anzsco_code: "399412", name: "Wood Machinist", assessing_authority: "VETASSESS" },
   { anzsco_code: "399511", name: "Chemical Plant Operator", assessing_authority: "VETASSESS" },
   { anzsco_code: "399512", name: "Gas or Petroleum Operator", assessing_authority: "VETASSESS" },
   { anzsco_code: "399513", name: "Power Generation Plant Operator", assessing_authority: "VETASSESS" },
   { anzsco_code: "399514", name: "Water and Waste Water Plant Operator", assessing_authority: "VETASSESS" },
   { anzsco_code: "399515", name: "Waste Water or Water Plant Operator", assessing_authority: "VETASSESS" },
   { anzsco_code: "399516", name: "Other Stationary Plant Operators nec", assessing_authority: "VETASSESS" },
   { anzsco_code: "399911", name: "Chemical Plant Operator", assessing_authority: "VETASSESS" },
   { anzsco_code: "399912", name: "Gas or Petroleum Operator", assessing_authority: "VETASSESS" },
   { anzsco_code: "399913", name: "Power Generation Plant Operator", assessing_authority: "VETASSESS" },
   { anzsco_code: "399914", name: "Water and Waste Water Plant Operator", assessing_authority: "VETASSESS" },
   { anzsco_code: "399915", name: "Waste Water or Water Plant Operator", assessing_authority: "VETASSESS" },
   { anzsco_code: "399999", name: "Other Technicians and Trades Workers nec", assessing_authority: "VETASSESS" },
];

// Helper functions for ANZSCO codes
export function getAnzscoCodesByAuthority(authority: string): AnzscoCode[] {
   return ANZSCO_CODES.filter((code) => code.assessing_authority === authority);
}

export function searchAnzscoCodes(query: string): AnzscoCode[] {
   if (!query) return ANZSCO_CODES;

   const lowerQuery = query.toLowerCase();
   return ANZSCO_CODES.filter(
      (code) =>
         code.anzsco_code.toLowerCase().includes(lowerQuery) ||
         code.name.toLowerCase().includes(lowerQuery) ||
         code.assessing_authority.toLowerCase().includes(lowerQuery)
   );
}

export function getAnzscoCodeByCode(anzscoCode: string): AnzscoCode | undefined {
   return ANZSCO_CODES.find((c) => c.anzsco_code === anzscoCode);
}

export function getUniqueAssessingAuthorities(): string[] {
   const authorities = new Set(ANZSCO_CODES.map((code) => code.assessing_authority));
   return Array.from(authorities).sort();
}